import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.scss']
})
export class SignupComponent implements OnInit {

  signupForm!: FormGroup;
  isWorker = false;
  loading = false;
  successMessage = '';
  errorMessage = '';
  registrationNoLoading = false;
  selfCodeLoading = false;
  selectedTitle = '';

  activeTab: 'registration' | 'payment' | 'done' = 'registration';

  /**
   * registrationNumber
   * Member → OurCode  (SMS-202504-0001) — generated on page load
   * Worker → SelfCode (WRK-001)         — generated on page load
   * Used as the DB lookup key when confirming UTR (sent in the UTR payload).
   */
  registrationNumber = '';

  /**
   * confirmationNumber — CONF-202504-0001
   * Generated by backend AFTER Register button is clicked.
   * Shown on Payment tab. Different series from registrationNumber.
   */
  confirmationNumber = '';

  /**
   * generatedSelfCode — WRK-001 (Worker only)
   * Auto-generated on page load. Pre-fills selfCode field readonly.
   */
  generatedSelfCode = '';

  isGuestPayment = false;

  // ── UPI deep-link helpers ──────────────────────────────────────────────────
  get upiLink(): string {
    const amt = this.isWorker ? '1200' : '200';
    return `upi://pay?pa=9594704311.etb@icici&pn=SMS Foundation&am=${amt}&cu=INR&tn=Registration Fee`;
  }
  get phonePeLink(): string {
    const amt = this.isWorker ? '1200' : '200';
    return `phonepe://pay?pa=9594704311.etb@icici&pn=SMS Foundation&am=${amt}&cu=INR&tn=Registration Fee`;
  }
  get gpayLink(): string {
    const amt = this.isWorker ? '1200' : '200';
    return `tez://upi/pay?pa=9594704311.etb@icici&pn=SMS Foundation&am=${amt}&cu=INR&tn=Registration Fee`;
  }
  get paytmLink(): string {
    const amt = this.isWorker ? '1200' : '200';
    return `paytmmp://pay?pa=9594704311.etb@icici&pn=SMS Foundation&am=${amt}&cu=INR&tn=Registration Fee`;
  }

  // ── API URLs ───────────────────────────────────────────────────────────────
  private apiUrl                    = 'https://vgfurnitureapi.runasp.net/api/Auth/register';
  private generateRegistrationNoUrl = 'https://vgfurnitureapi.runasp.net/api/Auth/generate-ourcode';
  private generateSelfCodeUrl       = 'https://vgfurnitureapi.runasp.net/api/Auth/generate-selfcode';
  private updateUtrUrl              = 'https://vgfurnitureapi.runasp.net/api/Auth/update-utr';
  private guestPaymentUrl           = 'https://vgfurnitureapi.runasp.net/api/Auth/record-guest-payment';

//   private apiUrl                    = 'https://localhost:7200/api/Auth/register';
// private generateRegistrationNoUrl = 'https://localhost:7200/api/Auth/generate-ourcode';
// private generateSelfCodeUrl       = 'https://localhost:7200/api/Auth/generate-selfcode';  // NEW
// private updateUtrUrl              = 'https://localhost:7200/api/Auth/update-utr';
// private guestPaymentUrl           = 'https://localhost:7200/api/Auth/record-guest-payment';


  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private http: HttpClient,
    private cdr: ChangeDetectorRef
  ) {}

  // ── Lifecycle ──────────────────────────────────────────────────────────────
  ngOnInit(): void {
    this.route.url.subscribe(segments => {
      this.isWorker = segments.some(s => s.path === 'worker');

      if (!this.signupForm) {
        this.buildForm();
        this.setConditionalValidators();
        this.setupTitleWatch();

        setTimeout(() => {
          if (!this.isWorker) {
            this.loadRegistrationNumber();   // Member: SMS-202504-0001
          } else {
            this.loadSelfCode();             // Worker: WRK-001
          }
        }, 100);
      }
    });
  }

  // ── Load Member OurCode on page load ──────────────────────────────────────
  loadRegistrationNumber(): void {
    if (!this.signupForm) { return; }

    this.registrationNoLoading = true;
    this.errorMessage = '';

    this.http.get<any>(this.generateRegistrationNoUrl, {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' })
    }).subscribe({
      next: (response) => {
        const code =
          response.ourCode            ||
          response.registrationNo     ||
          response.code               ||
          response.registrationNumber ||
          null;

        if (code) {
          this.registrationNumber = code;
          this.signupForm.patchValue({ registrationNo: code });
          this.signupForm.get('registrationNo')?.markAsTouched();
          this.signupForm.get('registrationNo')?.updateValueAndValidity();
        } else {
          this.errorMessage = 'Invalid response from server. Please refresh.';
        }

        this.registrationNoLoading = false;
        this.cdr.detectChanges();
      },
      error: (err: any) => {
        this.errorMessage = `Failed to load registration number: ${err.message || 'Please refresh.'}`;
        this.registrationNoLoading = false;
        this.cdr.detectChanges();
      }
    });
  }

  // ── Load Worker SelfCode on page load ─────────────────────────────────────
  loadSelfCode(): void {
    if (!this.signupForm) { return; }

    this.selfCodeLoading = true;
    this.errorMessage = '';

    this.http.get<any>(this.generateSelfCodeUrl, {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' })
    }).subscribe({
      next: (response) => {
        const code = response.selfCode || response.SelfCode || response.code || null;

        if (code) {
          this.generatedSelfCode = code;

          // ── KEY FIX: set registrationNumber to selfCode for Worker ──────
          // This is used later in the UTR payload as the DB lookup key.
          this.registrationNumber = code;

          this.signupForm.patchValue({ selfCode: code });
          this.signupForm.get('selfCode')?.markAsTouched();
          this.signupForm.get('selfCode')?.updateValueAndValidity();
        } else {
          this.errorMessage = 'Could not generate self code. Please refresh.';
        }

        this.selfCodeLoading = false;
        this.cdr.detectChanges();
      },
      error: (err: any) => {
        this.errorMessage = `Failed to generate worker code: ${err.message || 'Please refresh.'}`;
        this.selfCodeLoading = false;
        this.cdr.detectChanges();
      }
    });
  }

  // ── Tab switching — guarded by confirmationNumber ─────────────────────────
  switchTab(tab: 'registration' | 'payment' | 'done'): void {
    if (tab === 'payment' && !this.confirmationNumber && !this.isGuestPayment) { return; }
    if (tab === 'done'    && !this.confirmationNumber) { return; }
    this.activeTab = tab;
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  onGuestPaymentToggle(): void {
    this.cdr.detectChanges();
  }

  // ── Build Form ─────────────────────────────────────────────────────────────
  private buildForm(): void {
    const defaultAmount = this.isWorker ? 1200 : 200;

    this.signupForm = this.fb.group({
      title:       ['', Validators.required],
      fatherName:  [''],
      husbandName: [''],
      relation:    ['', Validators.required],
      nominee:     ['', Validators.required],
      fullName:    ['', Validators.required],
      dob:         ['', Validators.required],
      mobile:      ['', [Validators.required, Validators.pattern(/^[0-9]{10}$/)]],
      email:       ['', [Validators.required, Validators.email]],
      aadhar:      ['', [Validators.required, Validators.pattern(/^[0-9]{12}$/)]],
      pan:         ['', [Validators.pattern(/^[A-Z]{5}[0-9]{4}[A-Z]{1}$/)]],
      accountNo:   ['', [Validators.required, Validators.minLength(9), Validators.maxLength(20)]],
      address:     ['', Validators.required],

      skill:        [''],
      workArea:     [''],
      experience:   [''],
      availability: [''],

      designation: [''],

      // No Angular validators — validated manually in onSubmit()
      registrationNo:    [''],
      referenceName:     [''],
      referenceCode:     [''],
      selfCode:          [''],
      selfRankName:      [''],
      referenceRankName: [''],

      utr:    [''],
      amount: [defaultAmount, Validators.required],
      terms:  [false, Validators.requiredTrue],
    });
  }

  // ── Watch title changes ────────────────────────────────────────────────────
  private setupTitleWatch(): void {
    this.signupForm.get('title')?.valueChanges.subscribe((title: string) => {
      this.selectedTitle = title;

      const fatherCtrl  = this.signupForm.get('fatherName');
      const husbandCtrl = this.signupForm.get('husbandName');

      fatherCtrl?.clearValidators();
      husbandCtrl?.clearValidators();
      fatherCtrl?.setValue('');
      husbandCtrl?.setValue('');

      if (title === 'Mr' || title === 'Miss') {
        fatherCtrl?.setValidators([Validators.required]);
      } else if (title === 'Mrs') {
        husbandCtrl?.setValidators([Validators.required]);
      }

      fatherCtrl?.updateValueAndValidity();
      husbandCtrl?.updateValueAndValidity();
      this.cdr.detectChanges();
    });
  }

  // ── Conditional validators ─────────────────────────────────────────────────
  private setConditionalValidators(): void {
    if (this.isWorker) {
      ['skill', 'workArea', 'experience', 'availability'].forEach(f => {
        this.signupForm.get(f)?.setValidators(Validators.required);
        this.signupForm.get(f)?.updateValueAndValidity();
      });
      this.signupForm.get('designation')?.clearValidators();
      this.signupForm.get('designation')?.setValue('');
      this.signupForm.get('designation')?.updateValueAndValidity();
      this.signupForm.get('amount')?.setValue(1200);
    } else {
      ['skill', 'workArea', 'experience', 'availability'].forEach(f => {
        this.signupForm.get(f)?.clearValidators();
        this.signupForm.get(f)?.setValue('');
        this.signupForm.get(f)?.updateValueAndValidity();
      });
      this.signupForm.get('designation')?.setValidators(Validators.required);
      this.signupForm.get('designation')?.updateValueAndValidity();
      this.signupForm.get('amount')?.setValue(200);
    }

    // Always clear Angular validators from code/reference fields — manual only
    ['registrationNo', 'referenceName', 'referenceCode',
     'selfCode', 'selfRankName', 'referenceRankName'].forEach(f => {
      this.signupForm.get(f)?.clearValidators();
      this.signupForm.get(f)?.updateValueAndValidity();
    });
  }

  // ── Helpers ────────────────────────────────────────────────────────────────
  isInvalid(field: string): boolean {
    const control = this.signupForm.get(field);
    return !!(control && control.invalid && control.touched);
  }

  hasError(field: string, error: string): boolean {
    const control = this.signupForm.get(field);
    return !!(control && control.hasError(error) && control.touched);
  }

  toUpperCase(field: string): void {
    const control = this.signupForm.get(field);
    if (control) {
      control.setValue(control.value?.toUpperCase(), { emitEvent: false });
    }
  }

  onQrClick(event: MouseEvent): void {
    const isMobile = /Android|iPhone|iPad|iPod/i.test(navigator.userAgent);
    if (!isMobile) {
      event.preventDefault();
    }
  }

  onUtrInput(event: any): void {
    const value = event.target.value;
    const utrControl = this.signupForm.get('utr');
    if (utrControl) {
      utrControl.setValue(value, { emitEvent: false });
    }
  }

  getParentNameLabel(): string {
    if (this.selectedTitle === 'Mr' || this.selectedTitle === 'Miss') { return 'Father Name'; }
    if (this.selectedTitle === 'Mrs') { return 'Husband Name'; }
    return 'Parent Name';
  }

  private getInvalidAngularFields(): string[] {
    const codeFields = [
      'registrationNo', 'referenceName', 'referenceCode',
      'selfCode', 'selfRankName', 'referenceRankName'
    ];
    return Object.keys(this.signupForm.controls)
      .filter(key => !codeFields.includes(key) && this.signupForm.get(key)?.invalid)
      .map(key => `${key}: ${JSON.stringify(this.signupForm.get(key)?.errors)}`);
  }

  // ── Prepare DTO ────────────────────────────────────────────────────────────
  private prepareRegistrationData(): RegisterUserDto {
    const f = this.signupForm.getRawValue();

    let formattedDob = '';
    try {
      formattedDob = new Date(f.dob).toISOString().split('T')[0];
    } catch (e) {
      formattedDob = f.dob;
    }

    return {
      userType:      this.isWorker ? 'Worker' : 'Member',
      title:         f.title,
      fullName:      f.fullName?.trim(),
      fatherName:    (f.title === 'Mr' || f.title === 'Miss') ? (f.fatherName?.trim() || '') : '',
      husbandName:   f.title === 'Mrs' ? (f.husbandName?.trim() || '') : '',
      relation:      f.relation?.trim(),
      nominee:       f.nominee?.trim(),
      dateOfBirth:   formattedDob,
      mobileNumber:  f.mobile?.trim(),
      email:         f.email?.trim().toLowerCase(),
      aadhaarNumber: f.aadhar?.trim(),
      panNumber:     f.pan?.trim().toUpperCase() || null,
      accountNumber: f.accountNo?.trim(),
      address:       f.address?.trim(),
      skill:         f.skill            || null,
      workArea:      f.workArea?.trim() || null,
      experience:    f.experience       || null,
      availability:  f.availability     || null,
      designation:   this.isWorker ? null : (f.designation?.trim() || null),

      // ── KEY FIX ───────────────────────────────────────────────────────────
      // Member: send OurCode (SMS-202504-0001) in registrationNo
      // Worker: send SelfCode (WRK-001) in registrationNo
      //         Backend uses this as the RegistrationNo column value
      registrationNo: this.isWorker
        ? (f.selfCode?.trim() || this.generatedSelfCode || null)   // WRK-001
        : (f.registrationNo?.trim() || this.registrationNumber || null), // SMS-202504-0001

      // referenceName only for Member — Worker sends null
      referenceName: this.isWorker ? null : (f.referenceName?.trim() || null),

      referenceCode: f.referenceCode?.trim() || null,

      // Worker-only extra fields (stored elsewhere or informational)
      selfCode:          this.isWorker ? (f.selfCode?.trim()          || null) : null,
      selfRankName:      this.isWorker ? (f.selfRankName?.trim()      || null) : null,
      referenceRankName: this.isWorker ? (f.referenceRankName?.trim() || null) : null,

      utrNumber:     'PENDING',
      amount:        parseFloat(f.amount) || (this.isWorker ? 1200 : 200),
      termsAccepted: f.terms
    };
  }

  // ── Submit (Tab 1 → Tab 2) ─────────────────────────────────────────────────
  async onSubmit(): Promise<void> {
    Object.keys(this.signupForm.controls).forEach(key => {
      this.signupForm.get(key)?.markAsTouched();
    });

    this.errorMessage = '';

    // 1. Title
    const title = this.signupForm.get('title')?.value;
    if (!title) {
      this.errorMessage = 'Please select a title (Mr./Miss/Mrs.)';
      window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }

    // 2. Father / Husband name
    const fatherName  = this.signupForm.get('fatherName')?.value;
    const husbandName = this.signupForm.get('husbandName')?.value;

    if ((title === 'Mr' || title === 'Miss') && !fatherName?.trim()) {
      this.errorMessage = `Father name is required for ${title}.`;
      window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }
    if (title === 'Mrs' && !husbandName?.trim()) {
      this.errorMessage = 'Husband name is required for Mrs.';
      window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }

    // 3. Core personal fields
    const coreFields: { field: string; msg: string }[] = [
      { field: 'fullName',  msg: 'Full name is required.' },
      { field: 'dob',       msg: 'Date of birth is required.' },
      { field: 'mobile',    msg: 'Valid 10-digit mobile number is required.' },
      { field: 'email',     msg: 'Valid email address is required.' },
      { field: 'aadhar',    msg: 'Valid 12-digit Aadhaar number is required.' },
      { field: 'accountNo', msg: 'Bank account number is required (9-20 digits).' },
      { field: 'address',   msg: 'Address is required.' },
      { field: 'relation',  msg: 'Nominee name is required.' },
      { field: 'nominee',   msg: 'Relation is required.' },
    ];
    for (const item of coreFields) {
      if (this.signupForm.get(item.field)?.invalid) {
        this.errorMessage = item.msg;
        window.scrollTo({ top: 0, behavior: 'smooth' });
        return;
      }
    }

    // 4. Worker skill fields
    if (this.isWorker) {
      const workerFields: { field: string; msg: string }[] = [
        { field: 'skill',        msg: 'Skill is required.' },
        { field: 'workArea',     msg: 'Work area is required.' },
        { field: 'experience',   msg: 'Experience is required.' },
        { field: 'availability', msg: 'Availability is required.' },
      ];
      for (const item of workerFields) {
        if (this.signupForm.get(item.field)?.invalid) {
          this.errorMessage = item.msg;
          window.scrollTo({ top: 0, behavior: 'smooth' });
          return;
        }
      }
    }

    // 5. Member designation
    if (!this.isWorker) {
      if (!this.signupForm.get('designation')?.value?.trim()) {
        this.errorMessage = 'Designation is required.';
        window.scrollTo({ top: 0, behavior: 'smooth' });
        return;
      }
    }

    // 6. Member code fields
    if (!this.isWorker && !this.isGuestPayment) {
      const regNo = this.signupForm.getRawValue().registrationNo;
      if (!regNo?.trim() && !this.registrationNumber?.trim()) {
        this.errorMessage = 'Registration number not loaded. Please refresh the page.';
        window.scrollTo({ top: 0, behavior: 'smooth' });
        return;
      }
      if (!this.signupForm.get('referenceCode')?.value?.trim()) {
        this.errorMessage = 'Reference code is required.';
        window.scrollTo({ top: 0, behavior: 'smooth' });
        return;
      }
      if (!this.signupForm.get('referenceName')?.value?.trim()) {
        this.errorMessage = 'Reference name is required.';
        window.scrollTo({ top: 0, behavior: 'smooth' });
        return;
      }
    }

    // 7. Worker code fields
    if (this.isWorker) {
      // selfCode is auto-generated — check it loaded
      const selfCode = this.signupForm.get('selfCode')?.value?.trim() || this.generatedSelfCode;
      if (!selfCode) {
        this.errorMessage = 'Worker code not loaded. Please refresh the page.';
        window.scrollTo({ top: 0, behavior: 'smooth' });
        return;
      }
      if (!this.signupForm.get('selfRankName')?.value?.trim()) {
        this.errorMessage = 'Self rank name is required.';
        window.scrollTo({ top: 0, behavior: 'smooth' });
        return;
      }
      if (!this.signupForm.get('referenceCode')?.value?.trim()) {
        this.errorMessage = 'Reference code is required.';
        window.scrollTo({ top: 0, behavior: 'smooth' });
        return;
      }
      if (!this.signupForm.get('referenceRankName')?.value?.trim()) {
        this.errorMessage = 'Reference rank name is required.';
        window.scrollTo({ top: 0, behavior: 'smooth' });
        return;
      }
      // NOTE: referenceName is NOT validated for worker — it is not required
    }

    // 8. Terms
    if (!this.signupForm.get('terms')?.value) {
      this.errorMessage = 'You must accept the Terms & Conditions.';
      window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }

    // 9. Remaining Angular field validity
    const remainingInvalid = this.getInvalidAngularFields();
    if (remainingInvalid.length > 0) {
      console.error('Invalid fields:', remainingInvalid);
      this.errorMessage = 'Please fill all required fields correctly.';
      window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }

    // ── Call Register API ──────────────────────────────────────────────────
    this.loading = true;
    this.errorMessage = '';
    this.successMessage = '';

    const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

    try {
      const payload  = this.prepareRegistrationData();
      console.log('Register payload:', JSON.stringify(payload));

      const response = await firstValueFrom(
        this.http.post<ApiResponse>(this.apiUrl, payload, { headers })
      );

      this.loading = false;

      // registrationNumber = DB lookup key used in the UTR payload.
      // Member: OurCode  (SMS-202504-0001) - set on page load, keep it.
      // Worker: SelfCode (WRK-001)         - set on page load, keep it.
      //
      // The API response returns an INTERNAL number (SMSF/W/202604/0003)
      // in registrationNumber - we must NOT use that for UTR lookup.
      // Always use the page-load value; never overwrite from API response.
      if (this.isWorker) {
        // Always use SelfCode as the DB lookup key for Worker
        this.registrationNumber = this.generatedSelfCode;
      }
      // Member: this.registrationNumber was set in loadRegistrationNumber()
      // on page load and is already correct - no change needed.

      // confirmationNumber — CONF- series from backend
      const returnedConfNo =
        response.user?.confirmationNumber ||
        response.confirmationNumber        ||
        null;

      this.confirmationNumber = returnedConfNo || this.registrationNumber;

      this.successMessage =
        `Registration saved! Your Confirmation Number is ${this.confirmationNumber}. Please complete payment.`;

      setTimeout(() => {
        this.activeTab = 'payment';
        window.scrollTo({ top: 0, behavior: 'smooth' });
        this.cdr.detectChanges();
      }, 1200);

    } catch (error: any) {
      this.loading = false;

      if (error.status === 0) {
        this.errorMessage = 'Cannot reach the server. Please check your connection.';
      } else if (error.status === 400) {
        if (error.error?.errors) {
          const ve = error.error.errors as Record<string, string[]>;
          this.errorMessage = Object.values(ve).flat().join(' ');
        } else {
          this.errorMessage = error.error?.error ?? error.error?.message ?? 'Bad request. Please check your inputs.';
        }
      } else if (error.status === 409) {
        this.errorMessage = 'This email or Aadhaar is already registered.';
      } else if (error.status === 500) {
        this.errorMessage = 'Server error. Please try again later.';
      } else {
        this.errorMessage = error.error?.error ?? error.error?.message ?? 'Registration failed. Please try again.';
      }

      window.scrollTo({ top: 0, behavior: 'smooth' });
      this.cdr.detectChanges();
    }
  }

  // ── Confirm Payment (Tab 2 → Tab 3 + email) ───────────────────────────────
  async confirmPayment(): Promise<void> {
    const utrControl = this.signupForm.get('utr');
    let utrValue = utrControl?.value;

    if (!utrValue || utrValue.trim() === '') {
      const inputEl = document.querySelector('[formControlName="utr"]') as HTMLInputElement;
      if (inputEl && inputEl.value) {
        utrValue = inputEl.value;
        utrControl?.setValue(utrValue, { emitEvent: false });
      }
    }

    if (!utrValue || utrValue.toString().trim() === '') {
      this.errorMessage = 'Please enter the UTR / Transaction number before confirming.';
      window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }

    this.errorMessage   = '';
    this.successMessage = '';
    this.loading        = true;
    this.cdr.detectChanges();

    const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

    try {
      let payload: any;
      let url: string;

      if (this.isGuestPayment) {
        payload = {
          utrNumber:    utrValue.trim(),
          amount:       this.isWorker ? 1200 : 200,
          isGuest:      true,
          email:        this.signupForm.get('email')?.value,
          mobileNumber: this.signupForm.get('mobile')?.value
        };
        url = this.guestPaymentUrl;
      } else {
        // registrationNumber = OurCode (Member) or SelfCode (Worker)
        // Both stored in RegistrationNo column — backend finds the row by this value
        payload = {
          registrationNumber: this.registrationNumber,
          utrNumber:          utrValue.trim(),
          amount:             this.isWorker ? 1200 : 200
        };
        url = this.updateUtrUrl;
      }

      console.log('UTR payload:', JSON.stringify(payload));

      const response = await firstValueFrom(
        this.http.post<any>(url, payload, { headers })
      );

      this.loading = false;
      this.successMessage = response?.message ||
        'Payment confirmed! A confirmation email has been sent to your registered email.';

      if (this.isGuestPayment) {
        setTimeout(() => {
          this.activeTab      = 'registration';
          this.successMessage = 'Payment recorded! Please complete your registration.';
          this.cdr.detectChanges();
        }, 2000);
      } else {
        setTimeout(() => {
          this.activeTab = 'done';
          window.scrollTo({ top: 0, behavior: 'smooth' });
          this.cdr.detectChanges();
        }, 1000);
      }

    } catch (error: any) {
      this.loading = false;

      if (error.status === 0) {
        this.errorMessage = 'Cannot reach the server. Please check your connection.';
      } else if (error.status === 400) {
        this.errorMessage = error.error?.error || error.error?.message || 'Invalid UTR number. Please check and try again.';
      } else if (error.status === 404) {
        this.errorMessage = error.error?.error || 'Registration not found. Please contact support.';
      } else if (error.status === 409) {
        this.errorMessage = error.error?.error || 'UTR number already used.';
      } else if (error.status === 500) {
        this.errorMessage = 'Server error. Please try again later.';
      } else {
        this.errorMessage = error.error?.error || error.error?.message || 'Payment confirmation failed. Please try again.';
      }

      this.cdr.detectChanges();
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  }
}

// ── Interfaces ─────────────────────────────────────────────────────────────
interface RegisterUserDto {
  userType:          string;
  title:             string;
  fullName:          string;
  fatherName:        string;
  husbandName:       string;
  relation:          string;
  nominee:           string;
  dateOfBirth:       string;
  mobileNumber:      string;
  email:             string;
  aadhaarNumber:     string;
  panNumber:         string | null;
  accountNumber:     string;
  address:           string;
  skill:             string | null;
  workArea:          string | null;
  experience:        string | null;
  availability:      string | null;
  designation:       string | null;
  registrationNo:    string | null;
  referenceName:     string | null;
  referenceCode:     string | null;
  selfCode:          string | null;
  selfRankName:      string | null;
  referenceRankName: string | null;
  utrNumber:         string;
  amount:            number;
  termsAccepted:     boolean;
}

interface ApiResponse {
  message?:            string;
  registrationNumber?: string;
  confirmationNumber?: string;
  user?: {
    registrationNumber?: string;
    confirmationNumber?: string;
    [key: string]: any;
  };
}
